apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-data-pvc
  namespace: llmops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
  namespace: llmops
spec:
  replicas: 1

  selector:
    matchLabels:
      app: rag-api

  template:
    metadata:
      labels:
        app: rag-api

    spec:
      containers:
        - name: rag-api
          image: llmops-rag-api:1.0

          # Important for locally loaded KIND image
          imagePullPolicy: Never

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"


          envFrom:
            - configMapRef:
                name: llmops-config

            - secretRef:
                name: llmops-secret

          volumeMounts:
            - name: rag-data
              mountPath: /app/data

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20

      volumes:
        - name: rag-data
          persistentVolumeClaim:
            claimName: rag-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: rag-api
  namespace: llmops
spec:
  selector:
    app: rag-api

  ports:
    - port: 8000
      targetPort: 8000

  type: ClusterIP
