from prometheus_client import Counter, Histogram, Gauge


# ============================================================
# RAG METRICS
# ============================================================

rag_requests_total = Counter(
    "rag_requests_total",
    "Total number of RAG questions received"
)


rag_request_latency_seconds = Histogram(
    "rag_request_latency_seconds",
    "Total RAG request processing latency"
)


# ============================================================
# LLM REQUEST METRICS
# ============================================================

llm_requests_total = Counter(
    "llm_requests_total",
    "Total number of LLM generation requests"
)


llm_request_latency_seconds = Histogram(
    "llm_request_latency_seconds",
    "LLM generation request latency"
)


llm_ttft_seconds = Histogram(
    "llm_ttft_seconds",
    "Time to first token from the LLM"
)


# ============================================================
# TOKEN METRICS
# ============================================================

llm_prompt_tokens_total = Counter(
    "llm_prompt_tokens_total",
    "Total prompt tokens processed by the LLM"
)


llm_completion_tokens_total = Counter(
    "llm_completion_tokens_total",
    "Total completion tokens generated by the LLM"
)


llm_tokens_total = Counter(
    "llm_tokens_total",
    "Total LLM tokens processed"
)


# ============================================================
# COST METRICS
# ============================================================

llm_estimated_cost_usd_total = Counter(
    "llm_estimated_cost_usd_total",
    "Total estimated LLM cost in USD"
)


llm_last_request_estimated_cost_usd = Gauge(
    "llm_last_request_estimated_cost_usd",
    "Estimated cost in USD of the most recent LLM request"
)
